#玩家行为cd
action:
  #突破                
  levelUp: 5
  #破体
  bodyLevelUp: 5     
  #修改道宣
  autograph: 60
  #改名
  reName: 1240
  #重生         
  reborn: 360    
  #攻击
  attack: 5
  #击杀
  kill: 3

#玩家技能cd
skill:
  叶落归尘: 10
  红尘一梦: 10
  浮光掠影: 10
  镜花水月: 10
  狱火炼魂: 10
  天地同寿: 10
  终极伏特狂雷闪: 10
  绚烂缤纷花怒放: 10
  风雷鼓舞三千浪: 10
  九霄龙吟惊天变: 10
  封魔追魂烈焰斩: 10
  夤夜对雪长空断: 10
  大地荒芜崩山击: 10
  八卦游龙惊风破: 10
  极烈之枪: 10
  万法归一: 10